[package]
name = "sqlx_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8", features = [ "runtime-tokio", "postgres", "chrono" ] }
serde_json = { version = "1.0", features = ["raw_value"] }
dotenvy = "0.15"