services:
  database:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=sqlx_lib
    volumes:
      - database_data:/var/lib/postgresql/data
volumes:
  database_data:
    driver: local